#+BEGIN_COMMENT
.. title: 清华集训2017总结
.. slug: qing-hua-ji-xun-2017zong-jie
.. date: 2017-12-11 10:19:25 UTC+08:00
.. tags: mathjax, 游记
.. category: OI
.. link: 
.. description: 
.. type: text
#+END_COMMENT

被虐飞了.
#+BEGIN_HTML
<!--TEASER_END-->
#+END_HTML

**** day1
     先把三道题都看了一遍, 然后想了想最暴力能拿多少分, 发下T1会10分, T2会40分的
     插头dp, T3好像有很多部分分. 然后想了下T1怎么打 $O(n^3)$ 的暴力, 然后脑抽了
     没想出来, 于是把T1定义为不可做题, 写了10分就没管了. T2看上去像网络流, 但是
     想不出怎么建模. T3好象是一个大数据结构题, 先分块在并查集和树状数组维护. 于是
     想先把暴力打完再写T3. 无奈自己水平不够, 写前两题共50分暴力加起来用了2h. 然后
     纠结于写T3正解还是去拿暴力分. 我觉得自己可能码不出正解, 可能能够码出来的人也
     不多(哥哥这是集训队啊), 于是去一个部分分一个部分分地写, 结果写了3个部分分却
     怎么都只能拿7分, 我也很无奈, 然后就爆炸了.

     出成绩后发现T3 A了一片, T2也有很多人AC, 技不如人, 肝败吓疯.
     + *成绩* :: 57
     + *标准分* :: 82.6086957
**** day2
     看完三题之后感觉不好做, 然后看到T3的提示中写道 =题目顺序与难度无关=. 然后仔细
     想想好像可以 $O((160^3 + T160^2) \times \log{N})$ 做掉, 然后写了好久, 拿了90
     分, 感觉 $T$ 有500好像真的不太能过, 出题人肯定另有高论(结果是卡常, 优化取模). 
     然后发现自己拿不到什么分了. 

     过了会仔细想想发现 $T2$ 好像会 $O(n^2)$, 链的情况可以 $O(n \log{N})$, 然后
     开始码暴力, 链的情况还没过. 这时看到 =mcfx= 背上书包自信离场, 感觉自己要完.
     然后想T1, 先 =puts("0");= , 然后交上去就有了10分, 然后开始弃疗, 感觉应该是
     一道搜索题但是不知道怎么去打.

     出成绩发现T1, T2, T3都好多人AC. 然后数据好像有点水, =mcfx= T1随即化过了,
     =whzzt= T2从一开始枚举根dp直到超时也过了, 在IOI赛制下乱搞才是王道(雾)?

     + *成绩* :: 145
     + *标准分* :: 145
**** day3
     感觉T3一副可做的样子, 好像很多情况下只用两个质因子就会出现反例, 然后写了一下
     发现WA了, 打出来看了一下发现有一些不符合的情况, 于是如果不符合就打暴力枚举,
     然后好像跑得比时限大个几秒, 没关系, 我会打表, 然后70分get.
     
     其实上面这一段花了我2.5h, 代码异常凌乱. 然后感觉T2是个神奇的不平等博弈, 不会
     这套理论, 然后就是T1了, 只会打暴力.
     
     最后T1被A穿了, T3的题解是什么鬼. 最后一堆人还因为T3的spj撕了好久.
     + 成绩 :: 忘记了
     + 标准分 :: 146.511628
**** day4
     看到T3, 感觉可以做, 然后先写一个 $O(NM)$ 的暴力, 然后离散一下坐标就成了 $O(M^2)$.
     
     然后T1感觉可以找循环节, T2没有想法. 因为自己计算几何基本零基础, 所以写 $N=2$
     的部分分都写了很久, 并不能写出能够处理一般情况的方法. 然后T2的提示中写着
     =这是一道不太难的题=, 仿佛与day2T3如出一辙, 然后把剩下的时间都坑在这题上了.
     
     T2真的AC了一片, 然而我题解都没听太懂. T1也AC了一片. 我还是太菜了.
     
     + *成绩* :: 120
     + *标准分* :: 138.4615

**** 最终
+ *标准分* :: 21.35758
+ *集训队排名* :: 38
+ *与第15名的分差* :: 12.22768

感觉基本没戏了. 
